version: '3'
services:
  elasticsearch:
    build: .
    container_name: elasticsearch
    volumes:
      - ./es.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
    links:
      - "localstack:localstack"
    restart: always

  localstack:
    image: localstack/localstack:0.11.0
    container_name: localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-2
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=1234
      - AWS_SECRET_ACCESS_KEY=1234
    volumes:
      - './.localstack:/tmp/localstack'
